name: Build Project Aydin
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Mesin PS1 & Alat CD
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip cmake make build-essential genisoimage
          
          wget -q https://github.com/Lameguy64/PSn00bSDK/releases/download/v0.24/gcc-mipsel-none-elf-12.3.0-linux.zip
          wget -q https://github.com/Lameguy64/PSn00bSDK/releases/download/v0.24/PSn00bSDK-0.24-Linux.zip
          
          sudo unzip -q -o gcc-mipsel-none-elf-12.3.0-linux.zip -d /usr/local/
          sudo unzip -q -o PSn00bSDK-0.24-Linux.zip -d /usr/local/

      - name: Siapkan Konfigurasi CMake
        run: |
          TOOLCHAIN_PATH=$(find /usr/local -name "sdk.cmake" | head -n 1)
          echo "cmake_minimum_required(VERSION 3.21)" > CMakeLists.txt
          echo "set(CMAKE_TOOLCHAIN_FILE \"$TOOLCHAIN_PATH\")" >> CMakeLists.txt
          echo "project(AydinProject)" >> CMakeLists.txt
          echo "psn00bsdk_add_executable(aydin STATIC main.c)" >> CMakeLists.txt

      - name: Rakit Game & Bungkus ISO Aman
        run: |
          export PATH=$PATH:/usr/local/bin
          LIB_PATH=$(find /usr/local -type d -name "libpsn00b" | head -n 1)
          export PSN00BSDK_LIBS=$LIB_PATH
          
          mkdir build && cd build
          cmake ..
          make
          
          # Bersihin dan buat ulang folder cdroot
          rm -rf ../cdroot && mkdir -p ../cdroot
          
          # Salin file executable dan pastikan namanya kapital
          cp aydin.exe ../cdroot/AYDIN.EXE
          
          # Buat file SYSTEM.CNF standar PS1
          printf "BOOT = cdrom:\\\\AYDIN.EXE;1\r\nTCB = 4\r\nEVENT = 16\r\nSTACK = 801FFFF0\r\n" > ../cdroot/SYSTEM.CNF
          
          cd ..
          
          # Perintah genisoimage standar tanpa opsi aneh yang bikin error
          genisoimage -o aydin_game.iso -V "AYDIN_GAME" -no-emul-boot -iso-level 1 cdroot/

      - name: Simpan File Game ISO Siap Main
        uses: actions/upload-artifact@v4
        with:
          name: Game-Aydin-Jakarta-Utara-ISO
          path: aydin_game.iso
