name: Build Project Aydin
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Mesin PS1
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip cmake make build-essential
          
          wget -q https://github.com/Lameguy64/PSn00bSDK/releases/download/v0.24/gcc-mipsel-none-elf-12.3.0-linux.zip
          wget -q https://github.com/Lameguy64/PSn00bSDK/releases/download/v0.24/PSn00bSDK-0.24-Linux.zip
          
          sudo unzip -q -o gcc-mipsel-none-elf-12.3.0-linux.zip -d /usr/local/
          sudo unzip -q -o PSn00bSDK-0.24-Linux.zip -d /usr/local/

      - name: Siapkan Konfigurasi CMake
        run: |
          TOOLCHAIN_PATH=$(find /usr/local -name "sdk.cmake" | head -n 1)
          echo "cmake_minimum_required(VERSION 3.21)" > CMakeLists.txt
          echo "set(CMAKE_TOOLCHAIN_FILE \"$TOOLCHAIN_PATH\")" >> CMakeLists.txt
          echo "project(AydinProject)" >> CMakeLists.txt
          echo "psn00bsdk_add_executable(aydin STATIC main.c)" >> CMakeLists.txt

      - name: Rakit Game & Cetak Kaset Asli PS1
        run: |
          export PATH=$PATH:/usr/local/bin
          LIB_PATH=$(find /usr/local -type d -name "libpsn00b" | head -n 1)
          export PSN00BSDK_LIBS=$LIB_PATH
          
          mkdir build && cd build
          cmake ..
          make
          
          cd ..
          mkdir -p cd_root
          cp build/aydin.exe cd_root/AYDIN.EXE
          
          # Bikin file SYSTEM.CNF
          printf "BOOT = cdrom:\\\\AYDIN.EXE;1\r\nTCB = 4\r\nEVENT = 16\r\nSTACK = 801FFFF0\r\n" > cd_root/SYSTEM.CNF
          
          # Bikin cetakan XML buat alat pembuat kaset resmi
          echo '<?xml version="1.0" encoding="UTF-8"?>' > aydin.xml
          echo '<iso_project image_name="aydin_game.bin" cue_sheet="aydin_game.cue">' >> aydin.xml
          echo '  <track type="data">' >> aydin.xml
          echo '    <source>' >> aydin.xml
          echo '      <file name="SYSTEM.CNF" type="data" source="cd_root/SYSTEM.CNF" />' >> aydin.xml
          echo '      <file name="AYDIN.EXE" type="data" source="cd_root/AYDIN.EXE" />' >> aydin.xml
          echo '    </source>' >> aydin.xml
          echo '  </track>' >> aydin.xml
          echo '</iso_project>' >> aydin.xml
          
          # Cari dan jalankan alat pembuat kaset resmi dari PSn00bSDK
          MKPSXISO=$(find /usr/local -name "mkpsxiso" -type f | head -n 1)
          chmod +x $MKPSXISO
          $MKPSXISO aydin.xml

      - name: Simpan Kaset Game Siap Main
        uses: actions/upload-artifact@v4
        with:
          name: Game-Aydin-Kaset-Asli
          path: |
            aydin_game.bin
            aydin_game.cue
